name: Go

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    
    - name: Setup Redis
      uses: zhulik/redis-action@1.1.0
      
    - name: MongoDB
      uses: SusanDoggie/mongodb-action@0.0.1
      
    - name: Go Mod Download
      run: go mod download

    - name: Test Internal
      run: go test ./internal/...
      
    - name: Test Pkg
      run: go test ./pkg/...
      
    - name: Test Accounts Plugin
      run: go test -parallel 1 ./plugins/accounts/...
