name: Go

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Setup Redis
      uses: mjolnir-mud/redis-action@1.2.1

    - name: MongoDB
      uses: SusanDoggie/mongodb-action@0.0.1

    - name: Go Mod Download
      run: go mod download

    - name: Test
      run: go test -p 1 ./...
